# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skininfo',
            name='image',
            field=models.ImageField(upload_to='heroSkin', verbose_name='图片'),
        ),
    ]
